services:
  server:
    build: .
    container_name: bia
    ports:
      - 80:8080
    environment:
      DB_USER: postgres
      DB_PWD: v35IkAXr3dDoruopf4Tc
      DB_HOST: db-bia.cgrawk6w02jf.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
      